### ISSUE TITLE
Any way to run `Package Sync: Sync` from the command line?

### ISSUE THREAD

**Issue by simonvanderveldt** [lee-dohm/package-sync#25]
Hope it's OK, to ask this here.

Is there a way to run the `Package Sync: Sync` command from the command line?

P.S. I noticed your issue https://github.com/atom/atom/issues/5810 but that was met with a deafening silence :P Was hoping there was an alternative/some way to be able to do this.

P.P.S. Awesome package! Couldn't have created a proper version controlled config of Atom without it. Thanks!

**Comment by lee-dohm** [comment]
Definitely ok to ask questions here :grinning:

No, there isn't a way currently to run an Atom command from the command line. Adding the ability to execute this from the command line would be prohibitive because of that.

It was met with a silence because there are a bunch of other things that Atom needs to get right first :grinning: I posted it so that I wouldn't forget my crazy idea :laughing:

Thank you very much for the kind words! I'm glad you like the package :bow:

**Comment by simonvanderveldt** [comment]
Cool, thanks for the info! I'll +1 your Atom issue, who knows what will happen ;)
